# Generated by Django 5.0.3 on 2026-04-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('question', models.TextField()),
                ('correct_answer', models.TextField()),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('processing', 'Проверяется'), ('checked', 'Проверено'), ('error', 'Ошибка проверки'), ('timeout', 'Таймаут ответа')], default='pending', max_length=20)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('question_order', models.IntegerField()),
            ],
            options={
                'ordering': ['question_order'],
                'indexes': [models.Index(fields=['session_id', 'question_order'], name='lessons_int_session_c98d87_idx')],
            },
        ),
    ]
